// Mocks generated by Mockito 5.4.4 from annotations
// in moovup_test/test/data/repositories/poeple_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:moovup_test/data/data_sources/people_local_data_source.dart'
    as _i5;
import 'package:moovup_test/data/data_sources/people_remote_data_source.dart'
    as _i3;
import 'package:moovup_test/domain/entities/person.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakePerson_0 extends _i1.SmartFake implements _i2.Person {
  _FakePerson_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [PeopleRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockPeopleRemoteDataSource extends _i1.Mock
    implements _i3.PeopleRemoteDataSource {
  @override
  _i4.Future<List<_i2.Person>> getPeople() => (super.noSuchMethod(
        Invocation.method(
          #getPeople,
          [],
        ),
        returnValue: _i4.Future<List<_i2.Person>>.value(<_i2.Person>[]),
        returnValueForMissingStub:
            _i4.Future<List<_i2.Person>>.value(<_i2.Person>[]),
      ) as _i4.Future<List<_i2.Person>>);
}

/// A class which mocks [PeopleLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockPeopleLocalDataSource extends _i1.Mock
    implements _i5.PeopleLocalDataSource {
  @override
  _i4.Future<List<_i2.Person>> getPeople() => (super.noSuchMethod(
        Invocation.method(
          #getPeople,
          [],
        ),
        returnValue: _i4.Future<List<_i2.Person>>.value(<_i2.Person>[]),
        returnValueForMissingStub:
            _i4.Future<List<_i2.Person>>.value(<_i2.Person>[]),
      ) as _i4.Future<List<_i2.Person>>);

  @override
  _i4.Future<_i2.Person> getPerson(String? id) => (super.noSuchMethod(
        Invocation.method(
          #getPerson,
          [id],
        ),
        returnValue: _i4.Future<_i2.Person>.value(_FakePerson_0(
          this,
          Invocation.method(
            #getPerson,
            [id],
          ),
        )),
        returnValueForMissingStub: _i4.Future<_i2.Person>.value(_FakePerson_0(
          this,
          Invocation.method(
            #getPerson,
            [id],
          ),
        )),
      ) as _i4.Future<_i2.Person>);

  @override
  _i4.Future<void> savePeople(List<_i2.Person>? people) => (super.noSuchMethod(
        Invocation.method(
          #savePeople,
          [people],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}
